include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: false
    depend_on_referenced_packages: false
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
